from collections.abc import Callable
from pathlib import Path

import pytest

from app.server.packing.mcp import packing_checklist_ui
from app.server.travel_agent.mcp import (
    trip_board_ui,
    trip_budget_ui,
    trip_clarification_ui,
    trip_inbox_ui,
    trip_itinerary_ui,
)
from app.server.travel_tips.mcp import (
    travel_activity_cards_ui,
    travel_destination_guide_ui,
)
from app.server.weather.mcp import weather_dashboard_ui, weather_forecast_chart_ui


WEB_DIR = Path(__file__).resolve().parents[1] / "app" / "web"
DIST_WIDGETS = [
    "trip_inbox_v2.html",
    "trip_board_v3.html",
    "trip_itinerary_v3.html",
    "trip_budget_v3.html",
    "trip_clarification_v1.html",
]

LEGACY_WIDGETS: list[tuple[str, Callable[[], str], str]] = [
    ("ui://weather/dashboard-v5.html", weather_dashboard_ui, "Current weather"),
    ("ui://weather/forecast-chart-v2.html", weather_forecast_chart_ui, "5-day forecast"),
    ("ui://packing/checklist-v2.html", packing_checklist_ui, "Packing checklist"),
    ("ui://travel/destination-guide-v2.html", travel_destination_guide_ui, "Destination guide"),
    ("ui://travel/activity-cards-v2.html", travel_activity_cards_ui, "Activities"),
]

VITE_WIDGETS: list[tuple[str, Callable[[], str]]] = [
    ("ui://trip/inbox-v2.html", trip_inbox_ui),
    ("ui://trip/board-v3.html", trip_board_ui),
    ("ui://trip/itinerary-v3.html", trip_itinerary_ui),
    ("ui://trip/budget-v3.html", trip_budget_ui),
    ("ui://trip/clarification-v1.html", trip_clarification_ui),
]

def test_built_trip_widgets_exist_and_have_injections() -> None:
    dist_dir = WEB_DIR / "runtime_templates"
    if not dist_dir.exists():
        pytest.skip("app/web/runtime_templates is generated by npm run build")

    for filename in DIST_WIDGETS:
        html = (dist_dir / filename).read_text(encoding="utf-8")
        assert "<div id=\"root\"></div>" in html
        assert "<script type=\"module\">" in html
        assert "/src/entries/" not in html
        assert "@font-face" not in html
        assert "<script type=\"module\" crossorigin src=" not in html
        assert "<link rel=\"modulepreload\"" not in html
        assert "<link rel=\"stylesheet\"" not in html
        assert "from\"../chunks/" not in html
        assert "from\"/chunks/" not in html


def test_legacy_apps_ui_resources_are_complete_html_documents() -> None:
    for _uri, read_resource, expected_text in LEGACY_WIDGETS:
        html = read_resource()
        assert html.startswith("<!doctype html>")
        assert "<html" in html
        assert "<style>" in html
        assert "<script>" in html
        assert expected_text in html


def test_vite_apps_ui_resources_are_complete_html_documents() -> None:
    for _uri, read_resource in VITE_WIDGETS:
        html = read_resource()
        assert html.startswith("<!doctype html>")
        assert "<html" in html
        assert "<div id=\"root\"></div>" in html
        assert "<style>" in html
        assert "<script type=\"module\">" in html


def test_legacy_apps_ui_resources_are_self_contained() -> None:
    for _uri, read_resource, _expected_text in LEGACY_WIDGETS:
        html = read_resource()
        assert "http://" not in html
        assert "https://" not in html
        assert "<script src=" not in html
        assert "<link" not in html


def test_vite_apps_ui_resources_are_self_contained() -> None:
    for _uri, read_resource in VITE_WIDGETS:
        html = read_resource()
        assert "<script type=\"module\" crossorigin src=" not in html
        assert "<link rel=\"modulepreload\"" not in html
        assert "<link rel=\"stylesheet\"" not in html
        assert "from\"../chunks/" not in html
        assert "from\"/chunks/" not in html


def test_legacy_apps_ui_resources_include_bridge_update_handlers() -> None:
    for _uri, read_resource, _expected_text in LEGACY_WIDGETS:
        html = read_resource()
        assert "window.openai?.toolOutput" in html
        assert "openai:set_globals" in html
        assert "ui/notifications/tool-result" in html


def test_vite_apps_ui_resources_include_bridge_update_handlers() -> None:
    for _uri, read_resource in VITE_WIDGETS:
        html = read_resource()
        assert "toolOutput" in html
        assert "openai:set_globals" in html
        assert "ui/notifications/tool-result" in html


def test_trip_clarification_resource_includes_submit_and_close_bridge() -> None:
    html = trip_clarification_ui()

    assert "submit_trip_clarification" in html
    assert "session_json" in html
    assert "answers_json" in html
    assert "requestClose" in html
    assert "callTool" in html
    assert "sendFollowUpMessage" in html
    assert "setWidgetState" in html
    assert "ui/message" in html
    assert "tools/call" in html
    assert "prompt" in html
